package com.optiflow.operateur.order;

public enum OrderStatus {
    PENDING_VALIDATION,
    VALIDATED,
    REJECTED,
    PLANNED,
    IN_PROGRESS,
    IN_TRANSIT,
    DELIVERED,
    CANCELLATION_REQUESTED,
    CANCELLATION_PENDING,
    CANCELLED,
    CANCELLATION_REJECTED
}
